Refactor features
AT-08/trello-wdio-tests pull request #84
Opened 2019-01-11 22:59 UTC by RogerAlvarezM

2019-01-15 16:57 UTC, abelgustavo approved these changes

2019-01-15 18:07 UTC, DennisMont requested changes

2019-01-15 18:07 UTC, DennisMont commented on e2e/pages/common/sideBar.po.js
>    }
Please, create variables for the elements in commonActions and in return.

2019-01-16 18:44 UTC, DennisMont approved these changes

2019-01-16 18:44 UTC, merged